### ISSUE TITLE
Adding motion detection without PIR

### ISSUE THREAD

**Issue by thomas-pegot** [mtnbkr88/ESP32CAMVideoRecorder#1]
Hi,

>   - Motion detection is available if a PIR motion sensor is connected to GPIO3 (U0RXD)
>     (after the firmware is uploaded). 

I you are interested in motion detection from video, I developped an algo based on optical flow which can be used to detect motion detection for esp32cam. 

Link : https://github.com/thomas-pegot/esp32-motion

best,

**Comment by mtnbkr88** [comment]
Hi,

Yes, I am interested in motion detection without using PIR. I thought about trying this myself many months ago but haven't gotten around to it yet. The PIR I'm using gives tons of false positives on hot or windy days (my cameras are outside). Detecting motion from video could solve the false positives from heat but I think there's nothing that can be done for windy days (lots of tree movement). When I get the chance I'll take a look at what you've done.

Thanks!

________________________________

**Comment by thomas-pegot** [comment]
Ok take your time. 
I added a repo presenting the motion library : https://github.com/thomas-pegot/camera_web_server
peace
