### ISSUE TITLE
How we can get addres for the web server

### ISSUE THREAD

**Issue by Zulfahmi27** [mtnbkr88/ESP32CAMVideoRecorder#2]
Hi, could yoe help to get address for the web server

**Comment by mtnbkr88** [comment]
Hi. Between lines 190 and 219 is a section where you make changes for your network and other personal settings. Check them all and make the changes you need to for your situation. Line 196 is where you set the IP address you want for your web server on your network. Then just open your browser and go to that address. To access the Over The Air firmware update web page, go to <yourIPaddress>:90/updatefirmware.

**Comment by Zulfahmi27** [comment]
I have succeeded, Thanks@mtnbkr88, that's  very helpful

Regards

**Comment by mtnbkr88** [comment]
You're welcome.
