### ISSUE TITLE
pir motion detection

### ISSUE THREAD

**Issue by yousefhstm** [mtnbkr88/ESP32CAMVideoRecorder#4]
hi mtnbkr88 
1-great thank for you and your code skill
2-i upload the code and wire the circuit just like u say but madule donot take action ...even i measure the gpio 3 (it vas 0.6 volt )...how can i fix it? is it possible to change gpio 3 to low (input pulldown) and trigge it with pir(dout)?
3- some time my ESP32-CAM hangs(stick in reboot process) and the red led gose on continually (even after power off - on) until i program it with  standard EXAMPLE " CameraWebServer "that contain (define CAMERA_MODEL_AI_THINKER) then i can upload your code and get woke again ... it seem has issu with "ESP32 Wrover Module". how dose it fix?
thanks

**Comment by mtnbkr88** [comment]
Hi yousefhstm,
1 - Thank you
2 - I use GPIO 13 and this code to initialize it: pinMode(GPIO_NUM_13, INPUT_PULLDOWN); so it gets triggered when PIT (DOUT) goes high.
3 - The red light is supposed to stay on during the setup phase and turn off once it goes into the loop phase. It is strange that it hangs in the setup phase for you. I use Arduino 1.8.15 and "ESP32 Wrover Module" as the board and in the code I used the pin definitions for CAMERA_MODEL_AI_THINKER. Have you tried connecting your module to your PC and using the Serial Monitor to hopefully see where it is hanging? You might have to add Serial.println statements in various places to hopefully catch where it is getting stuck. That's what I do for these situations.
