### ISSUE TITLE
time trigger

### ISSUE THREAD

**Issue by yousefhstm** [mtnbkr88/ESP32CAMVideoRecorder#5]
hello dear mtnbkr88
 1_thanks for prev giude .it was help full and pir get work
2_ i wanna to take video or photo every 2min (for example) so i set "time trigger"at H=0 & M=2 but madule didnt take action...what can ido?
3_how can i turn the "SMD FLASH LAMP" off during madule work time?

**Comment by mtnbkr88** [comment]
Hi Yousefhstm,
1 - Glad you got it working.
2 - Time Trigger is used to wake up the ESP32 at a specific time once a day for 10 minutes. This allows a person to remotely connect to the ESP32 to change settings or update firmware. My ESP32 is sitting on a fence in the yard with a solar panel attached. Using the time trigger mine wakes up once a day at 13:00 so I can make changes to settings without going outside.
3 - The SMD FLASH LAMP is connected to pin 4. You can try the following in your setup function to turn off the LED:
  pinMode(4, OUTPUT);     // flash led on chip
  digitalWrite(4, LOW);   // turn off the flash LED on chip
However pin 4 is also one of the pins used to access the SD card so the white LED will flash when the SD card is accessed. There's nothing that can be done about that. If you find a schematic of the ESP32CAM you will find this to be so. If the flash is really bothering you put a piece of black electrical tape over it.

**Comment by yousefhstm** [comment]
Thanks

**Comment by yousefhstm** [comment]
if this code have ota , how can i use it?

**Comment by mtnbkr88** [comment]
Yes, this code has OTA. Here's how to use it:
1 - In the Arduino IDE choose Sketch->Export compiled binary. This will create the .bin file to upload.
2 - With the ESP32 being awake, go to http://<your_ip>/updatefirmware.
3 - Browse to and choose the .bin file saved above, enter the Update Password (the default is 12345678 if you did not change it) then choose Update.

**Comment by yousefhstm** [comment]
Thank you
